const { withDangerousMod } = require('expo/config-plugins')
const fs = require('fs')
const path = require('path')

/**
 * Patches the SplashScreen.storyboard generated by expo-splash-screen so its
 * declared image intrinsic size matches our actual phone-proportioned splash
 * image (1179×2556). The plugin hardcodes 414×736 (legacy iPhone 8 Plus),
 * which causes the LaunchScreen to render the image at a different aspect
 * than the runtime splash view — producing a visible jump at hand-off.
 */
module.exports = function withSplashScreenFix(config) {
  return withDangerousMod(config, [
    'ios',
    (config) => {
      const storyboardPath = path.join(
        config.modRequest.platformProjectRoot,
        config.modRequest.projectName,
        'SplashScreen.storyboard',
      )

      if (!fs.existsSync(storyboardPath)) return config

      let sb = fs.readFileSync(storyboardPath, 'utf8')
      sb = sb.replace(
        /<image name="SplashScreenLegacy" width="\d+" height="\d+"\/>/,
        '<image name="SplashScreenLegacy" width="393" height="852"/>',
      )
      fs.writeFileSync(storyboardPath, sb)

      return config
    },
  ])
}
